name: Deploy Skyler's Blog

on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      - uses: actions/checkout@v2 # 第一步，下载代码仓库

      - name: Set up node Env
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: build website
        run: |
          yarn install
          yarn build

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: /root/skyler-blog-website
          EXCLUDE: "/dist/, /node_modules/"

      # 我直接将打包好的产物，上传给服务器即可， 如果还需要在服务器上执行其他命令的话，配置下面的流程即可

      # - name: Restart server # 第三步，重启服务
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }} # 下面三个配置与上一步类似
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.DEPLOY_KEY }}
      #     # 重启的脚本，根据自身情况做相应改动，一般要做的是migrate数据库以及重启服务器
      #     script: |
      #       cd /home/fming/mysite/
      #       python manage.py migrate
      #       supervisorctl restart web
